modLoader="javafml"
loaderVersion="[32,)"

[[mods]]
modId="thermalconversion"
version="3.3.0"
displayName="Thermal Conversion"
displayURL="https://www.curseforge.com/minecraft/mc-mods/thermal-conversion"
issueTrackerURL="http://github.com/stuin/ThermalConversion/issues"
logoFile="cell2.png"
authors="Stuin"
description='''
Universal energy conversion through vanilla smelting mechanics.
'''
